DROP TABLE Reading_Info;
DROP TABLE Cal_Post;
DROP TABLE Review_Post;
DROP TABLE Member;

CREATE TABLE Member(
	MID     VARCHAR2(40)    NOT NULL,
	EMAIL	VARCHAR2(50)    NOT NULL,
	UPW	VARCHAR2(32)    NOT NULL,
	JOIN_DATE DATE NOT NULL
);
ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MID
);

CREATE TABLE Review_Post (
	RP_NO	NUMBER		NOT NULL,
	MID	VARCHAR2(40)		NOT NULL,
	RP_CONTENT	VARCHAR2(1000)		NOT NULL,
	RP_TITLE	VARCHAR2(100)		NOT NULL,
	RP_AUTHOR	VARCHAR2(50)		NOT NULL,
	READ_DATE	DATE		NOT NULL,
	REG_DATE	DATE		NOT NULL,
	PHRASE	VARCHAR(200)		NULL,
	RP_READ_CHECK	NUMBER(1)		NOT NULL
);
ALTER TABLE Review_Post ADD CONSTRAINT PK_REVIEW_POST PRIMARY KEY (
	RP_NO
);
COMMENT ON COLUMN Review_Post.RP_READ_CHECK IS '진행도를 체크하지 않는다(0), 진행도를 체크한다(1)';

CREATE TABLE Cal_Post (
	CP_NO	NUMBER		NOT NULL,
	MID	VARCHAR2(20)		NOT NULL,
	CP_TITLE	VARCHAR(50)		NOT NULL,
	CP_CONTENT	VARCHAR2(1000)		NOT NULL,
	CP_AUTHOR	VARCHAR2(50)		NOT NULL,
	CP_READ_CHECK	NUMBER(1)		NOT NULL,
	START1	DATE		NOT NULL,
	END1	DATE		NULL,
	ALLDAY	NUMBER(1)		NULL,
	TEXTCOLOR	VARCHAR(50)	NOT NULL,
	BACKGROUNDCOLOR	VARCHAR2(50)	NULL
);

ALTER TABLE Cal_Post ADD CONSTRAINT PK_CAL_POST PRIMARY KEY (
	CP_NO
);

COMMENT ON COLUMN Cal_Post.CP_READ_CHECK IS '체크하지 않는다(0), 읽는 중으로 체크(1), 완독으로 체크(2)';

COMMENT ON COLUMN Cal_Post.TEXTCOLOR IS 'DEFAULT BLACK';

COMMENT ON COLUMN Cal_Post.START1 IS '= (리뷰게시글)독서 시작일';

CREATE TABLE Reading_Info (
	MID	VARCHAR2(40)		NOT NULL,
	CP_NO	NUMBER		NOT NULL,
	TOTAL_PAGE	NUMBER		NULL,
	READ_PAGE	NUMBER		NULL,
	GENRE	VARCHAR2(30)		NULL
);

ALTER TABLE Reading_Info ADD CONSTRAINT PK_READING_INFO PRIMARY KEY (
	MID
);
ALTER TABLE Review_Post ADD CONSTRAINT FK_MEMBER_TO_Review_Post_1 FOREIGN KEY (
	MID
)
REFERENCES MEMBER (
	MID
);

ALTER TABLE Cal_Post ADD CONSTRAINT FK_MEMBER_TO_Cal_Post_1 FOREIGN KEY (
	MID
)
REFERENCES MEMBER (
	MID
);

ALTER TABLE Reading_Info ADD CONSTRAINT FK_MEMBER_TO_Reading_Info_1 FOREIGN KEY (
	MID
)
REFERENCES MEMBER (
	MID
);

ALTER TABLE Reading_Info ADD CONSTRAINT FK_Cal_Post_TO_Reading_Info_1 FOREIGN KEY (
	CP_NO
)
REFERENCES Cal_Post (
	CP_NO
);